import { StyleSheet } from 'react-native';

export const globalStyles = StyleSheet.create({
  container: { flex: 1 },
  section: { padding: 20 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 24, gap: 12 },
  sectionTitle: { fontSize: 28, fontWeight: '700' },
  refreshButton: { marginLeft: 'auto', padding: 8 },
  card: { borderRadius: 12, padding: 20, marginBottom: 16, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 1, shadowRadius: 4, elevation: 2 },
  cardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 16, gap: 12 },
  cardTitle: { fontSize: 20, fontWeight: '600' },
  statsRow: { flexDirection: 'row', justifyContent: 'space-around' },
  statItem: { alignItems: 'center' },
  statValue: { fontSize: 28, fontWeight: '700' },
  statLabel: { fontSize: 13, marginTop: 4 },
  statsGrid: { flexDirection: 'row', justifyContent: 'space-between' },
  statBox: { alignItems: 'center', flex: 1 },
  statBoxValue: { fontSize: 24, fontWeight: '700' },
  statBoxLabel: { fontSize: 12, marginTop: 4 },
  actionGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginTop: 8 },
  actionButton: { width: '48%', padding: 16, borderRadius: 12, marginBottom: 12, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 8 },
  buttonText: { fontWeight: '600', fontSize: 13 },
  learnCard: { flexDirection: 'row', alignItems: 'center' },
  learnIcon: { width: 50, height: 50, borderRadius: 25, alignItems: 'center', justifyContent: 'center', marginRight: 16 },
  learnContent: { flex: 1 },
  learnTitle: { fontSize: 17, fontWeight: '600', marginBottom: 4 },
  learnSummary: { fontSize: 14, lineHeight: 20, marginBottom: 8 },
  readMoreRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  readMore: { fontSize: 14, fontWeight: '500' },
  modalContainer: { flex: 1 },
  modalHeader: { padding: 16, borderBottomWidth: 0.5, alignItems: 'flex-start' },
  backButton: { paddingVertical: 8, flexDirection: 'row', alignItems: 'center', gap: 8 },
  backText: { fontSize: 16, fontWeight: '500' },
  modalContent: { flex: 1, padding: 20 },
  modalTitle: { fontSize: 28, fontWeight: '700', marginBottom: 24 },
  sectionSubtitle: { fontSize: 18, fontWeight: '600', marginBottom: 12 },
  sectionText: { fontSize: 15, lineHeight: 22, marginBottom: 16 },
  stepsList: { marginTop: 8 },
  stepItem: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 12 },
  stepNumber: { width: 24, height: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginRight: 12, marginTop: 2 },
  stepNumberText: { color: '#ffffff', fontWeight: '600', fontSize: 12 },
  stepText: { flex: 1, fontSize: 15, lineHeight: 22 },
  drillCard: { flexDirection: 'row', alignItems: 'center' },
  drillIconContainer: { width: 50, height: 50, borderRadius: 25, alignItems: 'center', justifyContent: 'center', marginRight: 16 },
  drillContent: { flex: 1 },
  drillTitle: { fontSize: 17, fontWeight: '600', marginBottom: 4 },
  drillSummary: { fontSize: 14, lineHeight: 20 },
  drillInstruction: { fontSize: 16, lineHeight: 24, marginBottom: 20 },
  primaryButton: { padding: 16, borderRadius: 10, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 8 },
  primaryButtonText: { color: '#ffffff', fontWeight: '600', fontSize: 16 },
  secondaryButton: { padding: 12, borderRadius: 10, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 8 },
  secondaryButtonText: { fontWeight: '600', fontSize: 14 },
  questionText: { fontSize: 17, lineHeight: 24, marginBottom: 20 },
  optionButton: { padding: 16, borderRadius: 8, marginBottom: 12, borderWidth: 1 },
  optionText: { fontWeight: '500', fontSize: 15 },
  scoreHeader: { alignItems: 'center', marginBottom: 16 },
  scoreText: { fontSize: 20, textAlign: 'center', marginVertical: 16, fontWeight: '600' },
  settingItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: 'rgba(0,0,0,0.05)' },
  settingLeft: { flexDirection: 'row', alignItems: 'center', flex: 1, gap: 16 },
  settingTextContainer: { flex: 1 },
  settingTitle: { fontSize: 16, fontWeight: '600' },
  pickerContainer: { marginTop: 8 },
  pickerLabel: { fontSize: 14, fontWeight: '600', marginBottom: 8 },
  pickerWrapper: { marginBottom: 8, overflow: 'hidden', borderWidth: 1, borderRadius: 8 },
  picker: { height: 50, width: '100%' },
  drawerHeader: { padding: 24, alignItems: 'center' },
  drawerHeaderTitle: { color: '#ffffff', fontSize: 20, fontWeight: '700', marginTop: 12 },
  drawerHeaderSubtitle: { color: '#ffffff', fontSize: 14, opacity: 0.8, marginTop: 4 },
  drawerSection: { paddingVertical: 12 },
  sectionLabel: { fontSize: 12, fontWeight: '600', marginLeft: 16, marginBottom: 8, letterSpacing: 1 },
  safetyTipText: { flex: 1, fontSize: 15, lineHeight: 22 },
  contactRow: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  contactInfo: { flex: 1 },
  contactName: { fontSize: 18, fontWeight: '600' },
  contactNumber: { fontSize: 16, fontWeight: '700', marginTop: 4 },
  callButton: { width: 44, height: 44, borderRadius: 22, justifyContent: 'center', alignItems: 'center' },
  emergencyButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', padding: 20, borderRadius: 12, marginBottom: 24, gap: 16 },
  emergencyButtonText: { color: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
  alertHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  alertTitle: { fontSize: 18, fontWeight: '700', flex: 1 },
  severityBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, marginLeft: 8 },
  severityText: { color: '#ffffff', fontWeight: 'bold', fontSize: 12 },
  alertArea: { fontSize: 14, fontWeight: '500', marginBottom: 8 },
  alertDescription: { fontSize: 15, lineHeight: 22 },
});
